version: '3.8'

services:
  mlflow:
    image: python:3.10
    working_dir: /app
    volumes:
      - .:/app
      - ./mlruns:/app/mlruns
    command: >
      bash -c "pip install --upgrade pip &&
               pip install -r requirements.txt &&
               mlflow ui --host 0.0.0.0 --port 5000"
    ports:
      - "5001:5000"

  shap_mlp:
    image: python:3.10
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "pip install --upgrade pip &&
              pip install pandas numpy scikit-learn imbalanced-learn matplotlib shap joblib pyarrow ctgan &&
              python interpretacion_shap.py"


