LogisticRegression:
  C: [0.1, 1, 10]

RandomForest:
  n_estimators: [50, 100]
  max_depth: [5, 10, null]

XGBoost:
  n_estimators: [50, 100]
  max_depth: [3, 6]

GradientBoosting:
  n_estimators: [50, 100]
  learning_rate: [0.01, 0.1]

KNN:
  n_neighbors: [3, 5, 7]

SVC:
  C: [0.1, 1]
  kernel: ['linear', 'rbf']

NaiveBayes: {}

MLP:
  hidden_layer_sizes: [[50], [100]]
  alpha: [0.0001, 0.01]
